"""PostgreSQL schema and one-time SQLite import for SchoolMS.

This module is deliberately separate from the local SQLite migrations.  It
creates only missing PostgreSQL objects and imports a read-only SQLite backup
inside one transaction, preserving primary keys and foreign-key relationships.
"""

from __future__ import annotations

import hashlib
import sqlite3
from pathlib import Path


APP_TABLES = (
    "users", "login_rate_limits", "classes", "subjects", "mobile_otp_sessions",
    "student_master_records", "teacher_master_records", "self_registration_otp_sessions",
    "email_registration_sessions", "firebase_profile_links", "fcm_device_tokens",
    "firebase_registration_sessions", "existing_email_migration_sessions", "student_profiles",
    "enrollments", "class_subjects", "attendance", "homework", "homework_submissions",
    "marks", "announcements", "facilities", "events", "timetable_entries", "admissions",
    "feedback", "media_assets", "gallery_items", "homework_student_targets",
    "content_attachments", "scheduled_tests", "scheduled_test_student_targets",
)


POSTGRES_SCHEMA = (
    """CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, full_name TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('admin','teacher','student')), email TEXT,
        email_verified_at DOUBLE PRECISION, phone TEXT, firebase_uid TEXT UNIQUE,
        activated INTEGER NOT NULL DEFAULT 1, must_change_password INTEGER NOT NULL DEFAULT 0,
        failed_login_attempts INTEGER NOT NULL DEFAULT 0, locked_until DOUBLE PRECISION
    )""",
    """CREATE TABLE IF NOT EXISTS login_rate_limits (
        identifier TEXT PRIMARY KEY, failed_attempts INTEGER NOT NULL DEFAULT 0,
        locked_until DOUBLE PRECISION
    )""",
    """CREATE TABLE IF NOT EXISTS classes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
        section TEXT NOT NULL, teacher_id BIGINT REFERENCES users(id)
    )""",
    """CREATE TABLE IF NOT EXISTS subjects (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
        code TEXT NOT NULL UNIQUE
    )""",
    """CREATE TABLE IF NOT EXISTS mobile_otp_sessions (
        token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        purpose TEXT NOT NULL CHECK(purpose IN ('activation','password_reset')), phone TEXT,
        provider_session_id TEXT NOT NULL, sent_at DOUBLE PRECISION NOT NULL,
        expires_at DOUBLE PRECISION NOT NULL, verify_attempts INTEGER NOT NULL DEFAULT 0
    )""",
    """CREATE TABLE IF NOT EXISTS student_master_records (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id TEXT UNIQUE NOT NULL,
        full_name TEXT NOT NULL, class_id BIGINT REFERENCES classes(id), roll_no TEXT, email TEXT,
        address TEXT, guardian_name TEXT, login_user_id BIGINT UNIQUE REFERENCES users(id),
        registration_completed INTEGER NOT NULL DEFAULT 0
    )""",
    """CREATE TABLE IF NOT EXISTS teacher_master_records (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, teacher_id TEXT UNIQUE NOT NULL,
        full_name TEXT NOT NULL, subject TEXT, login_user_id BIGINT UNIQUE REFERENCES users(id),
        registration_completed INTEGER NOT NULL DEFAULT 0
    )""",
    """CREATE TABLE IF NOT EXISTS self_registration_otp_sessions (
        token_hash TEXT PRIMARY KEY, role TEXT NOT NULL CHECK(role IN ('student','teacher')),
        master_record_id BIGINT NOT NULL, phone TEXT NOT NULL, provider_session_id TEXT NOT NULL,
        sent_at DOUBLE PRECISION NOT NULL, expires_at DOUBLE PRECISION NOT NULL,
        verify_attempts INTEGER NOT NULL DEFAULT 0
    )""",
    """CREATE TABLE IF NOT EXISTS email_registration_sessions (
        token_hash TEXT PRIMARY KEY, role TEXT NOT NULL CHECK(role IN ('student','teacher')),
        master_record_id BIGINT NOT NULL, email TEXT UNIQUE NOT NULL, firebase_uid TEXT UNIQUE NOT NULL,
        sent_at DOUBLE PRECISION NOT NULL, expires_at DOUBLE PRECISION NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS firebase_profile_links (
        firebase_uid TEXT NOT NULL, user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
        PRIMARY KEY(firebase_uid, user_id)
    )""",
    """CREATE TABLE IF NOT EXISTS fcm_device_tokens (
        token TEXT PRIMARY KEY, firebase_uid TEXT NOT NULL,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        platform TEXT NOT NULL DEFAULT 'android', created_at DOUBLE PRECISION NOT NULL,
        updated_at DOUBLE PRECISION NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS firebase_registration_sessions (
        token_hash TEXT PRIMARY KEY, role TEXT NOT NULL CHECK(role IN ('student','teacher')),
        master_record_id BIGINT NOT NULL, email TEXT NOT NULL, firebase_uid TEXT NOT NULL,
        email_already_verified INTEGER NOT NULL DEFAULT 0, sent_at DOUBLE PRECISION NOT NULL,
        expires_at DOUBLE PRECISION NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS existing_email_migration_sessions (
        token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
        email TEXT NOT NULL, firebase_uid TEXT NOT NULL, email_already_verified INTEGER NOT NULL DEFAULT 0,
        sent_at DOUBLE PRECISION NOT NULL, expires_at DOUBLE PRECISION NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS student_profiles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT UNIQUE NOT NULL REFERENCES users(id),
        class_id BIGINT REFERENCES classes(id), roll_no TEXT, email TEXT, phone TEXT, address TEXT,
        guardian_name TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS enrollments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, class_id BIGINT NOT NULL REFERENCES classes(id),
        student_id BIGINT NOT NULL REFERENCES users(id), UNIQUE(class_id, student_id)
    )""",
    """CREATE TABLE IF NOT EXISTS class_subjects (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, class_id BIGINT NOT NULL REFERENCES classes(id),
        subject_id BIGINT NOT NULL REFERENCES subjects(id), UNIQUE(class_id, subject_id)
    )""",
    """CREATE TABLE IF NOT EXISTS attendance (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id BIGINT NOT NULL REFERENCES users(id),
        class_id BIGINT NOT NULL REFERENCES classes(id), subject_id BIGINT NOT NULL REFERENCES subjects(id),
        attendance_date TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('present','absent')),
        marked_by BIGINT NOT NULL REFERENCES users(id),
        UNIQUE(student_id, class_id, subject_id, attendance_date)
    )""",
    """CREATE TABLE IF NOT EXISTS homework (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, class_id BIGINT NOT NULL REFERENCES classes(id),
        subject_id BIGINT NOT NULL REFERENCES subjects(id), teacher_id BIGINT NOT NULL REFERENCES users(id),
        title TEXT NOT NULL, description TEXT NOT NULL, due_date TEXT NOT NULL, file_name TEXT,
        created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text), section TEXT,
        target_mode TEXT NOT NULL DEFAULT 'class', instructions TEXT, external_link TEXT, assigned_date TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS homework_submissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, homework_id BIGINT NOT NULL REFERENCES homework(id),
        student_id BIGINT NOT NULL REFERENCES users(id), notes TEXT, file_name TEXT,
        submitted_at TEXT DEFAULT (CURRENT_TIMESTAMP::text), UNIQUE(homework_id, student_id)
    )""",
    """CREATE TABLE IF NOT EXISTS marks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id BIGINT NOT NULL REFERENCES users(id),
        class_id BIGINT NOT NULL REFERENCES classes(id), subject_id BIGINT NOT NULL REFERENCES subjects(id),
        exam_name TEXT NOT NULL, total_marks INTEGER NOT NULL, obtained_marks INTEGER NOT NULL,
        grade TEXT NOT NULL, entered_by BIGINT NOT NULL REFERENCES users(id)
    )""",
    """CREATE TABLE IF NOT EXISTS announcements (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, content TEXT NOT NULL,
        audience TEXT NOT NULL CHECK(audience IN ('all','admin','teacher','student')),
        created_by BIGINT NOT NULL REFERENCES users(id), created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text),
        image_url TEXT, cloudinary_public_id TEXT, media_asset_id BIGINT
    )""",
    """CREATE TABLE IF NOT EXISTS facilities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL,
        icon TEXT, created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text), image_url TEXT,
        cloudinary_public_id TEXT, media_asset_id BIGINT
    )""",
    """CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL,
        event_date TEXT NOT NULL, venue TEXT NOT NULL, created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text),
        image_url TEXT, cloudinary_public_id TEXT, media_asset_id BIGINT
    )""",
    """CREATE TABLE IF NOT EXISTS timetable_entries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, class_id BIGINT NOT NULL REFERENCES classes(id),
        subject_id BIGINT NOT NULL REFERENCES subjects(id), day_name TEXT NOT NULL, start_time TEXT NOT NULL,
        end_time TEXT NOT NULL, room TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS admissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_name TEXT NOT NULL, email TEXT NOT NULL,
        phone TEXT NOT NULL, applying_class TEXT NOT NULL, previous_school TEXT, message TEXT,
        status TEXT NOT NULL DEFAULT 'new', created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text)
    )""",
    """CREATE TABLE IF NOT EXISTS feedback (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL,
        category TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text)
    )""",
    """CREATE TABLE IF NOT EXISTS media_assets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id TEXT NOT NULL UNIQUE,
        secure_url TEXT NOT NULL, resource_type TEXT NOT NULL,
        delivery_type TEXT NOT NULL CHECK(delivery_type IN ('upload','private','authenticated')),
        file_format TEXT, original_filename TEXT NOT NULL, byte_size BIGINT NOT NULL DEFAULT 0,
        created_by BIGINT REFERENCES users(id), created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text)
    )""",
    """CREATE TABLE IF NOT EXISTS gallery_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL DEFAULT '',
        caption TEXT NOT NULL DEFAULT '', image_url TEXT NOT NULL, cloudinary_public_id TEXT,
        media_asset_id BIGINT REFERENCES media_assets(id), sort_order INTEGER NOT NULL DEFAULT 0,
        legacy_gallery_id TEXT, legacy_image_url TEXT, created_by BIGINT REFERENCES users(id),
        created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text), updated_at TEXT DEFAULT (CURRENT_TIMESTAMP::text)
    )""",
    """CREATE TABLE IF NOT EXISTS homework_student_targets (
        homework_id BIGINT NOT NULL REFERENCES homework(id) ON DELETE CASCADE,
        student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        PRIMARY KEY(homework_id, student_id)
    )""",
    """CREATE TABLE IF NOT EXISTS content_attachments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_type TEXT NOT NULL CHECK(owner_type IN ('homework','test')), owner_id BIGINT NOT NULL,
        media_asset_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
        display_name TEXT NOT NULL, created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text)
    )""",
    """CREATE TABLE IF NOT EXISTS scheduled_tests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, class_id BIGINT REFERENCES classes(id),
        section TEXT, subject_id BIGINT NOT NULL REFERENCES subjects(id), teacher_id BIGINT NOT NULL REFERENCES users(id),
        target_mode TEXT NOT NULL DEFAULT 'class', title TEXT NOT NULL, syllabus TEXT, instructions TEXT,
        test_date TEXT NOT NULL, start_time TEXT, end_time TEXT, maximum_marks INTEGER, external_link TEXT,
        result_published INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT (CURRENT_TIMESTAMP::text),
        updated_at TEXT DEFAULT (CURRENT_TIMESTAMP::text)
    )""",
    """CREATE TABLE IF NOT EXISTS scheduled_test_student_targets (
        test_id BIGINT NOT NULL REFERENCES scheduled_tests(id) ON DELETE CASCADE,
        student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        PRIMARY KEY(test_id, student_id)
    )""",
    """CREATE TABLE IF NOT EXISTS schema_migrations (
        migration_key TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""",
    """CREATE TABLE IF NOT EXISTS data_imports (
        import_key TEXT PRIMARY KEY, source_sha256 TEXT NOT NULL,
        imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )""",
)

POSTGRES_INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_mobile_otp_sessions_user_purpose ON mobile_otp_sessions(user_id, purpose, sent_at)",
    "CREATE INDEX IF NOT EXISTS idx_self_registration_otp_master ON self_registration_otp_sessions(role, master_record_id, sent_at)",
    "CREATE INDEX IF NOT EXISTS idx_firebase_profile_links_uid ON firebase_profile_links(firebase_uid)",
    "CREATE INDEX IF NOT EXISTS idx_fcm_device_tokens_profile ON fcm_device_tokens(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_media_assets_public_id ON media_assets(public_id)",
    "CREATE INDEX IF NOT EXISTS idx_gallery_items_sort ON gallery_items(sort_order, id)",
    "CREATE INDEX IF NOT EXISTS idx_content_attachments_owner ON content_attachments(owner_type, owner_id)",
    "CREATE INDEX IF NOT EXISTS idx_scheduled_tests_class_date ON scheduled_tests(class_id, test_date)",
    "CREATE INDEX IF NOT EXISTS idx_firebase_registration_master ON firebase_registration_sessions(role, master_record_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone ON users(phone) WHERE phone IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_firebase_uid ON users(firebase_uid) WHERE firebase_uid IS NOT NULL",
)


def migrate_postgres(db) -> None:
    """Idempotently create the final application schema in PostgreSQL."""
    for statement in POSTGRES_SCHEMA:
        db.execute(statement)
    for statement in POSTGRES_INDEXES:
        db.execute(statement)
    # Preserve every safe legacy one-to-one Firebase UID mapping. Shared-parent
    # identities are represented by firebase_profile_links and can be repaired
    # after the Firebase token proves ownership at sign-in time.
    db.execute(
        """INSERT INTO firebase_profile_links (firebase_uid, user_id)
        SELECT firebase_uid, id FROM users
        WHERE firebase_uid IS NOT NULL AND TRIM(firebase_uid) <> ''
        ON CONFLICT DO NOTHING"""
    )
    db.execute(
        "INSERT INTO schema_migrations (migration_key) VALUES (?) "
        "ON CONFLICT (migration_key) DO NOTHING",
        ("schoolms_postgres_schema_v1",),
    )
    _migrate_to_simple_class_model(db)
    db.commit()


def _migrate_to_simple_class_model(db) -> None:
    """Use the school's Class 1--Class 10 model without losing existing data.

    The original import contained two demonstration sections, Grade 10-A and
    Grade 10-B.  The real school uses one class per grade.  This one-time,
    transactional migration merges their references into Class 10 and creates
    Class 1 through Class 9 as empty, ready-to-configure classes.  It never
    deletes a student, homework item, mark, attendance record, or attachment.
    """
    migration_key = "schoolms_simple_class_model_v1"
    if db.execute("SELECT 1 FROM schema_migrations WHERE migration_key = ?", (migration_key,)).fetchone():
        return

    grade_ten_rows = db.execute(
        """SELECT id, teacher_id FROM classes
        WHERE LOWER(TRIM(name)) IN ('grade 10', 'class 10')
        ORDER BY id"""
    ).fetchall()

    if grade_ten_rows:
        primary_id = grade_ten_rows[0]["id"]
        db.execute("UPDATE classes SET name = ?, section = ? WHERE id = ?", ("Class 10", "", primary_id))
        for row in grade_ten_rows[1:]:
            duplicate_id = row["id"]
            # Preserve every relationship while avoiding the two existing
            # unique constraints on enrollments and class-subject mappings.
            db.execute(
                """DELETE FROM enrollments duplicate USING enrollments primary_row
                WHERE duplicate.class_id = ? AND primary_row.class_id = ?
                  AND primary_row.student_id = duplicate.student_id""",
                (duplicate_id, primary_id),
            )
            db.execute("UPDATE enrollments SET class_id = ? WHERE class_id = ?", (primary_id, duplicate_id))
            db.execute(
                """DELETE FROM class_subjects duplicate USING class_subjects primary_row
                WHERE duplicate.class_id = ? AND primary_row.class_id = ?
                  AND primary_row.subject_id = duplicate.subject_id""",
                (duplicate_id, primary_id),
            )
            db.execute("UPDATE class_subjects SET class_id = ? WHERE class_id = ?", (primary_id, duplicate_id))
            db.execute(
                """DELETE FROM attendance duplicate USING attendance primary_row
                WHERE duplicate.class_id = ? AND primary_row.class_id = ?
                  AND primary_row.student_id = duplicate.student_id
                  AND primary_row.subject_id = duplicate.subject_id
                  AND primary_row.attendance_date = duplicate.attendance_date""",
                (duplicate_id, primary_id),
            )
            for table in (
                "student_master_records", "student_profiles", "attendance",
                "homework", "marks", "timetable_entries", "scheduled_tests",
            ):
                db.execute(f"UPDATE {table} SET class_id = ? WHERE class_id = ?", (primary_id, duplicate_id))
            db.execute("DELETE FROM classes WHERE id = ?", (duplicate_id,))

    for number in range(1, 10):
        class_name = f"Class {number}"
        exists = db.execute(
            "SELECT 1 FROM classes WHERE LOWER(TRIM(name)) = LOWER(?) AND TRIM(section) = ''",
            (class_name,),
        ).fetchone()
        if not exists:
            db.execute("INSERT INTO classes (name, section) VALUES (?, ?)", (class_name, ""))

    # If there was no Grade 10 row, make the Class 10 record as well.
    if not db.execute(
        "SELECT 1 FROM classes WHERE LOWER(TRIM(name)) = LOWER(?) AND TRIM(section) = ''",
        ("Class 10",),
    ).fetchone():
        db.execute("INSERT INTO classes (name, section) VALUES (?, ?)", ("Class 10", ""))
    db.execute(
        "INSERT INTO schema_migrations (migration_key) VALUES (?) ON CONFLICT (migration_key) DO NOTHING",
        (migration_key,),
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _quote(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def sqlite_row_counts(source_path: str | Path) -> dict[str, int]:
    source = Path(source_path).resolve()
    connection = sqlite3.connect(f"{source.as_uri()}?mode=ro", uri=True)
    try:
        tables = {
            row[0] for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'"
            )
        }
        unexpected = tables.difference(APP_TABLES)
        if unexpected:
            raise RuntimeError(f"SQLite backup contains unsupported application tables: {', '.join(sorted(unexpected))}")
        return {table: connection.execute(f"SELECT COUNT(*) FROM {_quote(table)}").fetchone()[0] for table in APP_TABLES if table in tables}
    finally:
        connection.close()


def postgres_row_counts(db) -> dict[str, int]:
    return {table: db.execute(f"SELECT COUNT(*) AS count FROM {_quote(table)}").fetchone()["count"] for table in APP_TABLES}


def _reset_identity_sequences(db) -> None:
    for table in APP_TABLES:
        columns = db.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ? AND column_name = 'id'",
            (table,),
        ).fetchone()
        if columns:
            db.execute(
                "SELECT setval(pg_get_serial_sequence(?, 'id'), "
                "GREATEST(COALESCE((SELECT MAX(id) FROM " + _quote(table) + "), 1), 1), true)",
                (table,),
            )


def import_sqlite_backup_once(db, source_path: str | Path, import_key: str = "sqlite_backup_v1") -> dict[str, dict[str, int]]:
    """Import a verified, read-only SQLite backup exactly once.

    A previously imported identical backup is a no-op.  A non-empty PostgreSQL
    database without the import marker is rejected rather than merged.
    """
    source = Path(source_path).resolve()
    if not source.is_file():
        raise RuntimeError("SQLite import source does not exist.")
    source_hash = _sha256(source)
    source_counts = sqlite_row_counts(source)
    marker = db.execute("SELECT source_sha256 FROM data_imports WHERE import_key = ?", (import_key,)).fetchone()
    if marker:
        if marker["source_sha256"] != source_hash:
            raise RuntimeError("A different SQLite backup was already imported; refusing a duplicate merge.")
        return {"sqlite": source_counts, "postgres": postgres_row_counts(db)}

    destination_counts = postgres_row_counts(db)
    if any(destination_counts.values()):
        raise RuntimeError("PostgreSQL contains application data without an import marker; refusing to merge SQLite data.")

    source_connection = sqlite3.connect(f"{source.as_uri()}?mode=ro", uri=True)
    source_connection.row_factory = sqlite3.Row
    try:
        for table in APP_TABLES:
            if table not in source_counts:
                continue
            columns = [row[1] for row in source_connection.execute(f"PRAGMA table_info({_quote(table)})")]
            if not columns:
                continue
            rows = source_connection.execute(f"SELECT * FROM {_quote(table)}").fetchall()
            if not rows:
                continue
            column_sql = ", ".join(_quote(column) for column in columns)
            placeholders = ", ".join("?" for _ in columns)
            db.executemany(
                f"INSERT INTO {_quote(table)} ({column_sql}) VALUES ({placeholders}) ON CONFLICT DO NOTHING",
                (tuple(row[column] for column in columns) for row in rows),
            )
        _reset_identity_sequences(db)
        db.execute(
            "INSERT INTO data_imports (import_key, source_sha256) VALUES (?, ?)",
            (import_key, source_hash),
        )
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        source_connection.close()
    return {"sqlite": source_counts, "postgres": postgres_row_counts(db)}
